<a href="https://colab.research.google.com/github/konradplonka/machine-learning-bootcamp/blob/main/01_basics/01_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import bibliotek

In [2]:
import numpy as np
import pandas as pd
import sklearn

sklearn.__version__

'1.6.0'

# Wygenerowanie danych

In [3]:
data = data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}

df_raw = pd.DataFrame(data)
df_raw

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

# Utworzenie kopii danych

In [4]:
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 368.0+ bytes


# Zmiana typu danych

In [5]:
for col in ['size', 'color', 'gender', 'bought']:
  df[col] = df[col].astype('category')

df['weight'] = df['weight'].astype('float')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 740.0 bytes


In [6]:
df.describe().T

count   mean        std    min    25%    50%    75%    max
price     5.0  119.0  48.476799   79.0   89.0   99.0  129.0  199.0
weight    5.0  408.0  75.299402  300.0  380.0  410.0  450.0  500.0

In [7]:
df.describe(include=['category']).T

count unique     top freq
size       5      3       L    2
color      5      3   green    2
gender     5      2  female    3
bought     5      2     yes    3

# LabelEncoder

In [8]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit_transform(df['bought'])


array([1, 0, 1, 0, 1])

In [9]:
le.classes_

array(['no', 'yes'], dtype=object)

In [10]:
df['bought'] = le.fit_transform(df['bought'])
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

In [11]:
le.inverse_transform(df['bought'])

array(['yes', 'no', 'yes', 'no', 'yes'], dtype=object)

# OneHotEncoder

In [12]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)
encoder.fit(df[['size']])

OneHotEncoder(sparse_output=False)

In [13]:
encoder.transform(df[['size']])

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [14]:
encoder.categories_

[array(['L', 'M', 'XL'], dtype=object)]

In [15]:
encoder = OneHotEncoder(drop='first', sparse_output=False)
encoder.fit_transform(df[['size']])

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

# Pandas get_dummies()

In [16]:
pd.get_dummies(df)

price  weight  bought  size_L  ...  color_green  color_red  gender_female  gender_male
0  199.0   500.0       1   False  ...        False       True           True        False
1   89.0   450.0       0    True  ...         True      False          False         True
2   99.0   300.0       1   False  ...        False      False          False         True
3  129.0   380.0       0    True  ...         True      False           True        False
4   79.0   410.0       1   False  ...        False       True           True        False

[5 rows x 11 columns]

In [17]:
pd.get_dummies(df, drop_first=True)

price  weight  bought  size_M  size_XL  color_green  color_red  gender_male
0  199.0   500.0       1   False     True        False       True        False
1   89.0   450.0       0   False    False         True      False         True
2   99.0   300.0       1    True    False        False      False         True
3  129.0   380.0       0   False    False         True      False        False
4   79.0   410.0       1    True    False        False       True        False

# StandardScaler

In [18]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[['price', 'weight']] = scaler.fit_transform(df[['price', 'weight']])

df

size  color  gender     price    weight  bought
0   XL    red  female  1.845062  1.366002       1
1    L  green    male -0.691898  0.623610       0
2    M   blue    male -0.461266 -1.603567       1
3    L  green  female  0.230633 -0.415740       0
4    M    red  female -0.922531  0.029696       1

# Przygotowywanie danych do modelu

In [24]:
df = df_raw.copy()
label_encoder = LabelEncoder()

df['bought'] = label_encoder.fit_transform(df['bought'])

df = pd.get_dummies(df, drop_first=True)

scaler = StandardScaler()
df[['price','weight']] = scaler.fit_transform(df[['price', 'weight']])

df

price    weight  bought  size_M  size_XL  color_green  color_red  gender_male
0  1.845062  1.366002       1   False     True        False       True        False
1 -0.691898  0.623610       0   False    False         True      False         True
2 -0.461266 -1.603567       1    True    False        False      False         True
3  0.230633 -0.415740       0   False    False         True      False        False
4 -0.922531  0.029696       1    True    False        False       True        False